# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"
before_install:
  - "curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -"
  - sudo apt-get install --yes nodejs build-essential

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - npm install

# command to run tests, e.g. python setup.py test
script: npm run test && python setup.py test
